In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5])
arr2 = np.array([1, 2, 3, 4, 5, "Umar"])
arr3 = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
print(arr, arr.dtype, type(arr), arr.shape)
print(arr2, arr2.dtype, type(arr2), arr2.shape)
print(arr3, arr3.dtype, type(arr3), arr3.shape) # Dimensions have to be homogeneous too

[1 2 3 4 5] int32 <class 'numpy.ndarray'> (5,)
['1' '2' '3' '4' '5' 'Umar'] <U11 <class 'numpy.ndarray'> (6,)
[[1 2 3 4 5]
 [1 2 3 4 5]] int32 <class 'numpy.ndarray'> (2, 5)


In [3]:
arr4 = np.zeros((3,3))
print(arr4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
arr5 = np.ones((3,3), dtype = "int64") # You can also set the data type, it is floating by default.
print(arr5)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [5]:
arr6 = np.full((3,), 11) # Fill with any chosen value
print(arr6)

[11 11 11]


In [6]:
arr7 = np.eye(3) # To make an identity matrix
print(arr7)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
arr8 = np.arange(0, 11, 2) # Same as range in lists.
print(arr8)

[ 0  2  4  6  8 10]


In [8]:
arr9 = np.linspace(0, 100, 5, dtype="int64") # To create evenly spaced arrays in a particular range.
print(arr9)

[  0  25  50  75 100]


In [9]:
arr10 = np.array([1, 2, 3, 4, 5])
arr11 = arr10.astype(np.float64)
print(arr11, arr11.dtype)

[1. 2. 3. 4. 5.] float64
