In [1]:
# An image is represented as a 3D array: (height, width, channels)
# For RGB images, channels = 3 → [red, green, blue] at each pixel

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)
print(np.sum(arr))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45


In [2]:
# To print sum of columns

print(np.sum(arr, axis = 0)) # Here axis=0 means to apply the sum downwards and combine rows.
print(np.sum(arr, axis = 1)) 
print(arr[0:2, 0:3])

[12 15 18]
[ 6 15 24]
[[1 2 3]
 [4 5 6]]


In [3]:
# For 3d array now

arr3d = np.array([
    [[1, 2], [3, 4], [5, 6]],
    [[7, 8], [9, 10], [11, 12]]
])

print(arr3d.shape)
print(arr3d)

(2, 3, 2)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [4]:
print(arr3d[0, 1, 1])

4


In [6]:
print(arr3d[0:1, :, 0:1])

[[[1]
  [3]
  [5]]]


In [7]:
print(arr3d[ :, :, 0])

[[ 1  3  5]
 [ 7  9 11]]
