In [1]:
# Vectorisation - Normal lists in python are operated upon using loops, but through vectorisation in np arrays, we can apply the
# whole operation on the array in one go

In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])
print(arr**3)
print(arr - 1)
print(arr + arr2)

[  1   8  27  64 125]
[0 1 2 3 4]
[6 6 6 6 6]


In [3]:
# Braodcasting 
# Instead of copying data to match shapes, NumPy virtually expands the smaller array so element-wise operations can happen efficiently.
# Two arrays are compatible if, starting from the rightmost dimensions:
# Dimensions are equal, OR
# One of them is 1

In [4]:
a = np.ones((3, 1))   # (3,1)
b = np.ones((1, 4))   # (1,4)

print(a + b)          # (3,4)

[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]


In [5]:
# One of the uses of broadcasting is normalisation (fitting values to a certain scale or range)

In [6]:
# Normalising using z-score method
arr3 = np.array([[1, 2], [3, 4], [5, 6]])
mean = arr3.mean()
standard_deviation = arr3.std()
normal_array = (arr3-mean)/standard_deviation
print(normal_array)
print(normal_array.mean())

[[-1.46385011 -0.87831007]
 [-0.29277002  0.29277002]
 [ 0.87831007  1.46385011]]
-3.700743415417188e-17


In [7]:
# Maths functions
arr4 = np.array([1, 2, 3, 4, 5])

In [8]:
np.sum(arr4)

15

In [9]:
np.prod(arr4)

120

In [10]:
np.min(arr4)

1

In [11]:
np.max(arr4)

5

In [12]:
np.mean(arr4)

3.0

In [13]:
np.std(arr4)

1.4142135623730951

In [14]:
np.var(arr4)

2.0

In [15]:
np.median(arr4)

3.0

In [16]:
np.argmin(arr4)

0

In [17]:
np.argmax(arr4)

4

In [18]:
np.square(arr4)

array([ 1,  4,  9, 16, 25])

In [19]:
np.sqrt(arr4)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [20]:
np.power(arr4, 2)

array([ 1,  4,  9, 16, 25], dtype=int32)

In [21]:
arr4 = np.array([1.2, 2.7, 3.5, 4.9, 5.1])

In [22]:
np.round(arr4)

array([1., 3., 4., 5., 5.])

In [23]:
np.floor(arr4)

array([1., 2., 3., 4., 5.])

In [24]:
np.ceil(arr4)

array([2., 3., 4., 5., 6.])

In [25]:
np.trunc(arr4)

array([1., 2., 3., 4., 5.])

In [26]:
arr4 = np.array([1, 2, 3, 4, 5])
arr4

array([1, 2, 3, 4, 5])

In [27]:
np.log(arr4)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [28]:
np.log10(arr4)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ])

In [29]:
np.log2(arr4)

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809])

In [30]:
np.exp(arr4)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [31]:
arr4 = np.array([1, 2, 2, 3, 4, 4, 5])
arr4

array([1, 2, 2, 3, 4, 4, 5])

In [32]:
np.unique(arr4)

array([1, 2, 3, 4, 5])

In [33]:
np.sort(arr4)

array([1, 2, 2, 3, 4, 4, 5])

In [34]:
arr4 = np.array([-1, -2, 3, -4, 5])
np.abs(arr4)

array([1, 2, 3, 4, 5])